name: Build libhighs for Android

on:
  workflow_dispatch:
  push:
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/build-android.yml"
      - "src/**"

jobs:
  android:
    name: Android ABIs
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        preset: [android-arm64, android-arm32, android-x64, android-x86]
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Setup JDK (required by NDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true

      - name: Show NDK env
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_HOME" >> $GITHUB_ENV

      - name: Configure (${{ matrix.preset }})
        run: cmake --preset ${{ matrix.preset }}

      - name: Build (${{ matrix.preset }})
        run: cmake --build --preset ${{ matrix.preset }} --config Release

      - name: Collect .so into plugin layout
        run: |
          set -e
          OUT=out-android/${{ matrix.preset }}
          mkdir -p $OUT/android/src/main/jniLibs
          case "${{ matrix.preset }}" in
            android-arm64) ABI=arm64-v8a ;;
            android-arm32) ABI=armeabi-v7a ;;
            android-x64)   ABI=x86_64 ;;
            android-x86)   ABI=x86 ;;
          esac
          mkdir -p $OUT/android/src/main/jniLibs/$ABI
          # Adjust the path below if your target name / output dir differs
          cp build-${{ matrix.preset }}/lib/libhighs.so $OUT/android/src/main/jniLibs/$ABI/

      - name: Upload artifact (${{ matrix.preset }})
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.preset }}
          path: out-android/${{ matrix.preset }}

  package:
    name: Package plugin layout
    needs: [android]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: _artifacts

      - name: Prepare combined layout
        run: |
          set -e
          mkdir -p pkg/android/src/main/jniLibs
          # copy ABIs
          find _artifacts -type d -name jniLibs -exec rsync -a {}/ pkg/android/src/main/jniLibs/ \;

      - name: Zip deliverable
        run: |
          (cd pkg && zip -r ../dart-highs-prebuilt-lib-android.zip .)

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: dart-highs-prebuilt-lib-android
          path: dart-highs-prebuilt-lib-android.zip
