name: Build libhighs for iOS

on:
  workflow_dispatch:
  push:
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/build-ios.yml"
      - "highs/**"
      - "build_scripts/**"
      - "build.py"

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  PYTHON_VERSION: "3.11"
  BUILD_CONFIG: "Release"
  XCFRAMEWORK_NAME: "LibHighs"
  PACKAGE_NAME: "dart-highs-prebuilt-lib-ios"

jobs:
  build-individual:
    name: iOS ${{ matrix.platform }}
    runs-on: macos-14
    strategy:
      matrix:
        platform: [ios-arm64, ios-simulator-arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Ninja
        run: brew install ninja

      - name: Select Xcode 16.2 (supports iOS 18.2 SDK)
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build platform using build script
        run: |
          python build.py build ${{ matrix.platform }} --config ${{ env.BUILD_CONFIG }} --extract-libs

      - name: Upload individual library
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: highs_patched/build-${{ matrix.platform }}/libhighs.a

  build-xcframework:
    name: iOS XCFramework
    runs-on: macos-14
    needs: [build-individual]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Ninja
        run: brew install ninja

      - name: Select Xcode 16.2 (supports iOS 18.2 SDK)
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build XCFramework using build script
        run: |
          python build.py build ios --config ${{ env.BUILD_CONFIG }}

      - name: Upload XCFramework
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcframework
          path: highs_patched/build/ios-xcframework/highs.xcframework

  package:
    name: Package iOS Release
    needs: [build-individual, build-xcframework]
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: _artifacts

      - name: List downloaded artifacts
        run: find _artifacts -type f | sort

      - name: Package individual libraries
        run: |
          mkdir -p pkg-individual/ios
          
          # Package individual architectures
          cp -r _artifacts/ios-arm64 pkg-individual/ios/
          cp -r _artifacts/ios-simulator-arm64 pkg-individual/ios/
          
          # Create zip for individual libraries
          (cd pkg-individual && zip -r ../${{ env.PACKAGE_NAME }}-individual.zip .)

      - name: Package XCFramework
        run: |
          mkdir -p pkg-xcframework/ios
          cp -r _artifacts/ios-xcframework/highs.xcframework pkg-xcframework/ios/${{ env.XCFRAMEWORK_NAME }}.xcframework
          
          # Create zip for XCFramework
          (cd pkg-xcframework && zip -r ../${{ env.PACKAGE_NAME }}.zip .)

      - name: Upload individual package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-individual
          path: ${{ env.PACKAGE_NAME }}-individual.zip

      - name: Upload XCFramework package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.PACKAGE_NAME }}.zip

      - name: Create iOS release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ios-v${{ github.run_number }}-${{ github.sha }}
          name: HiGHS iOS Libraries
          body: |
            HiGHS prebuilt libraries for iOS platforms
            
            This release contains:
            
            **XCFramework (Recommended)**:
            - `${{ env.PACKAGE_NAME }}.zip` - Complete XCFramework supporting both device and simulator
            - Ready to drag-and-drop into Xcode projects
            
            **Individual Libraries**:
            - `${{ env.PACKAGE_NAME }}-individual.zip` - Separate .a files for each architecture
            - `ios-arm64/` - iOS device library (ARM64)
            - `ios-simulator-arm64/` - iOS simulator library (ARM64)
            
            **Usage:**
            For most users, download the XCFramework package and add `${{ env.XCFRAMEWORK_NAME }}.xcframework` to your iOS project.
            
            Generated from commit: ${{ github.sha }}
            Build configuration: ${{ env.BUILD_CONFIG }}
          files: |
            ${{ env.PACKAGE_NAME }}.zip
            ${{ env.PACKAGE_NAME }}-individual.zip
          draft: false
          prerelease: false
