name: Build libhighs for Android

on:
  workflow_dispatch:
  push:
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/build-android.yml"
      - "src/**"

jobs:
  build:
    name: Android (${{ matrix.preset }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        preset: [android-arm64, android-arm32, android-x64, android-x86]
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Setup JDK (required by NDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          add-to-path: true

      - name: Show NDK env
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_HOME" >> $GITHUB_ENV

      - name: Configure (${{ matrix.preset }})
        run: cmake --preset ${{ matrix.preset }}

      - name: Build (${{ matrix.preset }})
        run: cmake --build --preset ${{ matrix.preset }} --config Release

      - name: Upload library artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}
          path: build-${{ matrix.preset }}/lib/libhighs.so

  assemble:
    name: Assemble Android Libraries
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: _artifacts

      - name: List downloaded artifacts
        run: find _artifacts -type f -name "*.so" | sort

      - name: Assemble Android plugin layout
        run: |
          set -e
          mkdir -p out-android/android/src/main/jniLibs
          
          # Map preset names to Android ABI names and copy libraries
          declare -A abi_map=(
            ["android-arm64"]="arm64-v8a"
            ["android-arm32"]="armeabi-v7a"
            ["android-x64"]="x86_64"
            ["android-x86"]="x86"
          )
          
          for preset in android-arm64 android-arm32 android-x64 android-x86; do
            abi=${abi_map[$preset]}
            mkdir -p out-android/android/src/main/jniLibs/$abi
            cp _artifacts/$preset/libhighs.so out-android/android/src/main/jniLibs/$abi/
            echo "Copied $preset -> $abi"
          done

      - name: Upload Android bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-bundle
          path: out-android/

  package:
    name: Package plugin layout
    needs: [assemble]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android-bundle
          path: _artifacts

      - name: Prepare combined layout
        run: |
          set -e
          # copy Android libraries
          mkdir -p pkg/android/src/main/jniLibs
          cp -R _artifacts/android/src/main/jniLibs/* pkg/android/src/main/jniLibs/

      - name: Zip deliverable
        run: |
          (cd pkg && zip -r ../dart-highs-prebuilt-lib-android.zip .)

      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: dart-highs-prebuilt-lib-android
          path: dart-highs-prebuilt-lib-android.zip

      - name: Create Android release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: android-v${{ github.run_number }}-${{ github.sha }}
          name: HiGHS Android Libraries
          body: |
            HiGHS prebuilt libraries for Android platforms
            
            This release contains native libraries for all Android ABIs:
            - arm64-v8a (Android 64-bit ARM)
            - armeabi-v7a (Android 32-bit ARM)
            - x86_64 (Android 64-bit Intel)
            - x86 (Android 32-bit Intel)
            
            **Usage:**
            Extract the zip file and integrate the `android/src/main/jniLibs` structure into your Android project.
            
            Generated from commit: ${{ github.sha }}
          files: dart-highs-prebuilt-lib-android.zip
          draft: false
          prerelease: false