name: Build libhighs for Windows

on:
  workflow_dispatch:
  push:
    paths:
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/build-windows.yml"
      - "highs/**"
      - "build_scripts/**"
      - "build.py"

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  PYTHON_VERSION: "3.11"
  BUILD_CONFIG: "Release"
  PACKAGE_NAME: "dart-highs-prebuilt-lib-windows"

jobs:
  build:
    name: Windows x64
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v2

      - name: Build using build script
        run: |
          python build.py build windows-x64 --config ${{ env.BUILD_CONFIG }} --extract-libs

      - name: Upload library artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: highs_patched/build/windows-x64/highs.dll

  package:
    name: Package Windows Library
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: _artifacts

      - name: Package library
        run: |
          mkdir -p pkg/windows
          cp _artifacts/windows-x64/highs.dll pkg/windows/

      - name: Create zip
        run: |
          (cd pkg && zip -r ../${{ env.PACKAGE_NAME }}.zip .)

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.PACKAGE_NAME }}.zip
